name: manga_reader_app
description: "Kizuna - Manga Reading application made in Flutter"
publish_to: 'none'

version: 1.0.4+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # network
  http: ^1.2.2
  cached_network_image: ^3.4.1
  # supabase
  supabase_flutter: ^2.9.1
  # bloc
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  # connectivity
  connectivity_plus: ^6.1.5
#  # intl
  intl: ^0.20.2
  # hive
  hive_ce: ^2.8.0+2
  hive_ce_flutter: ^2.1.0
  # path_provider
  path_provider: ^2.1.5
  # utils
  file_picker: ^10.3.2
  gal: ^2.3.2
  font_awesome_flutter: ^10.8.0
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  flutter_local_notifications: ^19.4.1
  workmanager: ^0.9.0+2
  collection: ^1.19.1
  lottie: ^3.3.1
  envied: ^1.2.1
  # listview for reading page
  scrollable_positioned_list: ^0.3.8
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_ce_generator: ^1.8.1
  envied_generator: ^1.2.1


flutter:
  uses-material-design: true
  assets:
    - assets/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
