// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:manga_reader_app/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ArtistAdapter());
    registerAdapter(AuthorAdapter());
    registerAdapter(ChapterAdapter());
    registerAdapter(ChaptersDataModelAdapter());
    registerAdapter(GenreAdapter());
    registerAdapter(MangaAdapter());
    registerAdapter(ReadingStatusAdapter());
    registerAdapter(UserMangaAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ArtistAdapter());
    registerAdapter(AuthorAdapter());
    registerAdapter(ChapterAdapter());
    registerAdapter(ChaptersDataModelAdapter());
    registerAdapter(GenreAdapter());
    registerAdapter(MangaAdapter());
    registerAdapter(ReadingStatusAdapter());
    registerAdapter(UserMangaAdapter());
  }
}
